[build]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH", 
  "apt-get update && apt-get --assume-yes install fuse:$CROSS_DEB_ARCH libfuse:$CROSS_DEB_ARCH",
  "echo 'user_allow_other' | tee -a /etc/fuse.conf"
]     
